TARGET = viewbmp

CC = gcc
CFLAGS = -Wall -g -I/usr/include/SDL2
LIBS = -L/usr/lib/local -lSDL2main -lSDL2

all:  viewbmp.o
	$(CC) $(CFLAGS) -o $(TARGET) viewbmp.o $(LIBS)

viewbmp.o: viewbmp.c
	$(CC) $(CFLAGS) -c viewbmp.c

clean:
	rm -f $(TARGET) viewbmp.o

run: $(TARGET)
	./$(TARGET)
