TARGET = main

CC = gcc
CFLAGS = -Wall -g -I/usr/include/SDL2
LIBS = -L/usr/lib/local -lSDL2main -lSDL2

all:  main.o
	$(CC) $(CFLAGS) -o $(TARGET) main.o $(LIBS)

main.o: main.c
	$(CC) $(CFLAGS) -c main.c

clean:
	rm -f $(TARGET) main.o

run: $(TARGET)
	./$(TARGET)
