TARGET = viewbmp
OBJS = viewbmp.o romdisk.o
KOS_ROMDISK_DIR = romdisk
 
# Update include paths for SDL3
#KOS_CFLAGS+= -I../../../../build-scripts/build/include -I../../../../build-scripts/build/include-config-/SDL3 -I../../../../build-scripts/build/include/SDL3 -I. -DDREAMCAST

#KOS_CFLAGS+= -O3 -ffast-math -fno-common -fno-builtin -fno-exceptions -fstrict-aliasing 

#KOS_CPPFLAGS=-fno-operator-names -fno-exceptions $(KOS_CFLAGS) 

# Update library paths and libraries for SDL3
#KOS_LIBS+= -L../../../../build-scripts/build -lSDL3 -lSDL3main

all: $(TARGET).bin

include $(KOS_BASE)/Makefile.rules

clean:
	rm -f $(OBJS) $(TARGET).elf $(TARGET).bin romdisk.img

$(TARGET).elf: $(OBJS)
	kos-cc -DDREAMCAST -o $(TARGET).elf $(OBJS) -lSDL3  -lm -lkosutils -lpthread

$(TARGET).bin: $(TARGET).elf
	$(KOS_OBJCOPY) -O binary $(TARGET).elf $(TARGET).bin

run: $(TARGET).bin 
	$(KOS_LOADER) $(TARGET).bin
